version: '3.9'
networks:
  app-net:

volumes:
  hardhat_artifacts:
  grafana_data:
  sqlite_data:

services:
  api:
    build: ./backend
    env_file:
      - ./.env.development
    ports:
      - "3001:3001"
    networks:
      - app-net
    volumes:
      - sqlite_data:/app/data

  ml:
    build: ./ml-service
    env_file:
      - ./.env.development
    ports:
      - "8000:8000"
    networks:
      - app-net

  hardhat:
    build: ./hardhat
    ports:
      - "8545:8545"
    volumes:
      - ./hardhat:/app
      - hardhat_artifacts:/app/artifacts
    networks:
      - app-net

  nuxt:
    build: ./nuxt-app
    env_file:
      - ./.env.development
    environment:
      HOST: 0.0.0.0
      DB_DIR: /app
    ports:
      - "3000:3000"
    depends_on:
      - api
      - ml
      - hardhat
    volumes:
      - hardhat_artifacts:/app/artifacts:ro
      - sqlite_data:/app/data
    networks:
      - app-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - app-net

  grafana:
    image: grafana/grafana
    ports:
      - "3005:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-net
