version: '3.8'
services:
  nuxt:
    build: ./nuxt-app
    ports:
      - "3000:3000"
    environment:
      CHAIN_RPC_URL: http://hardhat:8545
      ML_SERVICE_URL: http://ml:8000/score
    depends_on:
      - hardhat
      - ml
    networks:
      - app-network
  hardhat:
    image: node:18
    working_dir: /app
    volumes:
      - ./nuxt-app:/app
    command: npx hardhat node
    ports:
      - "8545:8545"
    networks:
      - app-network
  ml:
    build: ./ml
    ports:
      - "8000:8000"
    networks:
      - app-network
networks:
  app-network:
