version: '3.8'
services:
  nuxt:
    build: ./nuxt-app
    ports:
      - "3000:3000"
    environment:
      CHAIN_RPC_URL: http://hardhat:8545
    depends_on:
      - hardhat
  hardhat:
    image: node:18
    working_dir: /app
    volumes:
      - ./nuxt-app:/app
    command: npx hardhat node
    ports:
      - "8545:8545"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - nuxt
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
